# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NXWJKnZF-7eOT9XYPixjle8JNy9trAyJ
"""

import json
import re
def register():
    email_id = input("Enter your e-mail:")
    pattern1 = '^[A-Za-z0-9._%+-]+@[A-Za-z0-9]+\.[A-Z|a-z]{2,3}$'
    pattern2 = '^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%*]).{5,16}$'
    while True:
        if re.search(pattern1,email_id) == None:
            print('E-mail is Invalid !!!')
            print("eg:- sherlock@gmail.com")
            email_id = input("Please enter a valid email:")
        else:
            break
    password = input("Enter your password:")
    while True:
        if re.search(pattern2,password) == None:
            print('Password is Invalid !!!')
            print("It Should contain minimum One Special character,\nOne Digit,\nOne Uppercase,\nOne Lowercase,\nMinimum length 5 to 16 ")
            password = input("Please enter a valid password:")
        else:
            print("Successfully registered !!!")
            break
    with open('details.txt', mode = 'a') as file:
        str1 = '{ "email": "' + email_id + '", "pwd":"' + password + '" }'+'\n'
        file.write(str1)
        
        
def login():
    email_id = input("Enter your e-mail:")
    password = input("Enter your password:")
    with open('details.txt') as file:
        for line in file:
            check = json.loads(line)
            if check['email'] == email_id:
                if check['pwd'] == password:
                    print('Login Successful !!!')
                    break
                else:
                    forget = int(input("Did you forget password\n 1 - Yes 2 - No"))
                    if forget == 1:
                        print('Your password is:',check['pwd'])
                        break
                    else:
                        break
            
            else:
                print("Email is not registered !!!.\nWould you like to register? 1-Yes 2-No")
                reg = int(input())
                if reg == 1:
                    register()
                    break
                else:
                    break


while True:
    print("Please select an option:\n 1 - Register\n 2 - Login \n 3 - Exit")
    num = int(input())
    if num == 1:
        register()
    elif num == 2:
        login()
    else:
        break

from google.colab import drive
drive.mount('/content/drive')